site_name: 'Labs Engineering Standards'
site_description: 'Engineering standards guide for Lambda School Labs'
repo_name: 'Lambda-School-Labs/labs-engineering-standards'
repo_url: 'https://github.com/Lambda-School-Labs/labs-engineering-standards'

markdown_extensions:
    - tables
    - admonition
    - codehilite
    - toc:
        permalink: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.details

theme:
  name: 'material'

nav:
    - Home: 'index.md'
    - Writing Standards: topics/writing-standards.md
    - Developer Workflow: topics/developer-workflow.md
    - Programming Languages: topics/programming-languages.md
    - React: topics/react.md
    - Node.js: topics/node-js.md
    - Git: topics/git.md
    - GitHub: topics/github.md
    - Code Quality: topics/code-quality.md
    - Data Persistence: topics/data-persistence.md
    - Third Party Services: topics/third-party-services.md
    - Web API Frameworks: topics/web-api-frameworks.md
    - Security: topics/security.md
